name: 'mou-docker-action'
author: 'MindDoc Health GmbH'
branding:
  icon: 'anchor'
  color: 'blue'
description: 'Uses the git branch or tag as the docker tag and pushes the built image'
inputs:
  name:
    description: 'The name of the image you would like to push'
    required: true
  username:
    description: 'The login username for the registry'
    required: true
  password:
    description: 'The login password for the registry'
    required: true
  registry:
    description: 'Use registry for pushing to a custom registry'
    required: false
  dockerfile:
    description: 'Use dockerfile when you would like to explicitly build a Dockerfile'
    required: false
  workdir:
    description: 'Use workdir when you would like to change the directory for building'
    required: false
  buildargs:
    description: 'Use buildargs when you want to pass a list of environment variables as build-args'
    required: false
  cache:
    description: 'Use cache when you have big images, that you would only like to build partially'
    required: false
  tags:
    description: 'Use tags when you want to add additional tags to the docker image'
    required: false
outputs:
  sha-tag:
    description: 'Is the tag, which was pushed and refers to the commit sha'
  ref-tag:
    description: 'Is the tag that is generated from the detected and sanitized ref that is pushed'
runs:
  using: 'docker'
  image: 'Dockerfile'
